import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TextInput,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
  Modal,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { Image as ExpoImage } from 'expo-image';
import { useAuth } from '@/contexts/AuthContext';
import {
  getDefaultWardrobeId,
  createWardrobeItem,
} from '@/lib/wardrobe';
import { triggerAutoTag, triggerProductShot, triggerAIJobExecution, pollAIJobWithFinalCheck } from '@/lib/ai-jobs';

export default function AddItemScreen() {
  const { user } = useAuth();
  const router = useRouter();
  const [wardrobeId, setWardrobeId] = useState<string | null>(null);
  const [selectedImages, setSelectedImages] = useState<Array<{ uri: string; type: string; name: string }>>([]);
  const [loading, setLoading] = useState(false);
  const [initializing, setInitializing] = useState(true);
  const [generatingAI, setGeneratingAI] = useState(false);
  const [aiJobId, setAiJobId] = useState<string | null>(null);

  useEffect(() => {
    initialize();
  }, [user]);

  // Removed category/subcategory selection logic - AI will recognize them

  const initialize = async () => {
    if (!user) return;

    setInitializing(true);
    
    // Get default wardrobe
    const { data: defaultWardrobeId } = await getDefaultWardrobeId(user.id);
    if (defaultWardrobeId) {
      setWardrobeId(defaultWardrobeId);
    }

    // Categories no longer needed - AI will recognize them
    setInitializing(false);
  };

  // Removed loadSubcategories - no longer needed

  const handleTakePhoto = async () => {
    const { status } = await ImagePicker.requestCameraPermissionsAsync();
    if (status !== 'granted') {
      Alert.alert('Permission Required', 'Please grant camera permissions');
      return;
    }

    const mediaTypes = (ImagePicker as any).MediaType?.Images || 'images';

    const result = await ImagePicker.launchCameraAsync({
      mediaTypes,
      allowsEditing: true,
      quality: 0.8,
    });

    if (result.canceled || !result.assets[0]) return;

    // Use uriToBlob for proper file:// handling on iOS
    const { uriToBlob } = await import('@/lib/wardrobe');
    const newImage = {
      uri: result.assets[0].uri,
      type: result.assets[0].type || 'image/jpeg',
      name: result.assets[0].fileName || `photo-${Date.now()}.jpg`,
    };
    setSelectedImages([...selectedImages, newImage]);
  };

  const handleUploadPhoto = async () => {
    const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    
    if (status !== 'granted') {
      Alert.alert('Permission Required', 'Please grant camera roll permissions to upload images');
      return;
    }

    // On web, MediaType may not exist, so use string fallback
    const mediaTypes = ImagePicker.MediaType?.Images || 'images';

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes,
      allowsMultipleSelection: true,
      quality: 0.8,
    });

    if (!result.canceled && result.assets) {
      const newImages = result.assets.map((asset) => ({
        uri: asset.uri,
        type: asset.type || 'image/jpeg',
        name: asset.fileName || `image-${Date.now()}.jpg`,
      }));
      setSelectedImages([...selectedImages, ...newImages]);
    }
  };

  const handleCreateFromLink = () => {
    Alert.alert('Coming Soon', 'Creating items from links will be available soon!');
  };

  const removeImage = (index: number) => {
    setSelectedImages(selectedImages.filter((_, i) => i !== index));
  };

  const handleSubmit = async () => {
    if (!user || !wardrobeId) {
      Alert.alert('Error', 'Please sign in to add items');
      return;
    }

    if (selectedImages.length === 0) {
      Alert.alert('Error', 'Please select at least one image');
      return;
    }

    setLoading(true);

    try {
      // Visibility will be set by AI if needed (e.g., Intimates category)

      // Use placeholder title - AI will replace it when generation completes
      // Category and subcategory will be recognized by AI
      const { data, error } = await createWardrobeItem(
        user.id,
        wardrobeId,
        {
          title: 'New Item', // Placeholder - will be replaced by AI
          description: undefined, // Will be generated by AI
          category_id: undefined, // Will be recognized by AI
          subcategory_id: undefined, // Will be recognized by AI
          visibility_override: 'inherit', // Default, can be updated by AI if needed
        },
        selectedImages
      );

      if (error) {
        Alert.alert('Error', error.message || 'Failed to create item');
      } else {
        // Create and auto-trigger product_shot and auto_tag jobs
        if (data?.item && data?.images && data.images.length > 0) {
          try {
            const imageIds = data.images.map((img: any) => img.image_id);

            // Create product shot job for first image (auto-triggered)
            const { data: productShotJob, error: productShotError } = await triggerProductShot(
              user.id,
              imageIds[0],
              data.item.id
            );

            // Auto-trigger the product shot job immediately
            if (productShotJob && !productShotError) {
              const execResult = await triggerAIJobExecution(productShotJob.id);
            } else if (productShotError) {
              console.warn('Failed to create product shot job:', productShotError);
            }

            // Create auto_tag job (auto-triggered) - AI will recognize category/subcategory
            const { data: autoTagJob, error: autoTagError } = await triggerAutoTag(
              user.id,
              data.item.id,
              imageIds,
              null, // No category provided - AI will recognize it
              null  // No subcategory provided - AI will recognize it
            );

            // Auto-trigger the auto_tag job immediately
            if (autoTagJob && !autoTagError) {
              const execResult = await triggerAIJobExecution(autoTagJob.id);
              if (!execResult.error) {
                // Show loading dialog and poll for completion
                setGeneratingAI(true);
                setAiJobId(autoTagJob.id);
                
                // Poll for auto_tag completion (30 attempts = ~60 seconds)
                // Wait for completion before navigating so user sees results immediately
                try {
                  await pollAIJobWithFinalCheck(autoTagJob.id, 30, 2000);
                  
                  // Navigate after polling completes (whether success, failure, or timeout)
                  setGeneratingAI(false);
                  setAiJobId(null);
                  router.replace(`/wardrobe/item/${data.item.id}`);
                } catch (error) {
                  // Navigate even on error
                  setGeneratingAI(false);
                  setAiJobId(null);
                  router.replace(`/wardrobe/item/${data.item.id}`);
                }
              } else {
                // Trigger failed - navigate anyway
                router.replace(`/wardrobe/item/${data.item.id}`);
              }
            } else if (autoTagError) {
              console.warn('Failed to create auto-tag job:', autoTagError);
              // Navigate even if job creation failed
              router.replace(`/wardrobe/item/${data.item.id}`);
            } else {
              // No auto_tag job - navigate immediately
              router.replace(`/wardrobe/item/${data.item.id}`);
            }

            // Note: Product shot job runs asynchronously
            // Results will be applied when jobs complete via Netlify function
          } catch (error) {
            console.warn('Error triggering AI jobs:', error);
            // Don't fail the whole operation if AI jobs fail
            setGeneratingAI(false);
            setAiJobId(null);
            router.replace(`/wardrobe/item/${data.item.id}`);
          }
        } else {
          // No images - navigate immediately
          router.replace(`/wardrobe/item/${data.item.id}`);
        }
      }
    } catch (error: any) {
      Alert.alert('Error', error.message || 'An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  if (initializing) {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" style={styles.loader} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* Header with Back button */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.headerButton}>
          <Text style={styles.headerButtonText}>← Back</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        <Text style={styles.title}>Add Wardrobe Item</Text>

      <View style={styles.section}>
        <Text style={styles.label}>Images *</Text>
        
        {selectedImages.length === 0 ? (
          <View style={styles.imageOptionsContainer}>
            <TouchableOpacity style={styles.optionButton} onPress={handleTakePhoto}>
              <Ionicons name="camera-outline" size={32} color="#007AFF" />
              <View style={styles.optionTextContainer}>
                <Text style={styles.optionTitle}>Take Photo</Text>
                <Text style={styles.optionSubtext}>Use your camera</Text>
              </View>
              <Ionicons name="chevron-forward" size={24} color="#ccc" />
            </TouchableOpacity>

            <TouchableOpacity style={styles.optionButton} onPress={handleUploadPhoto}>
              <Ionicons name="images-outline" size={32} color="#007AFF" />
              <View style={styles.optionTextContainer}>
                <Text style={styles.optionTitle}>Upload Photo</Text>
                <Text style={styles.optionSubtext}>Choose from library</Text>
              </View>
              <Ionicons name="chevron-forward" size={24} color="#ccc" />
            </TouchableOpacity>

            <TouchableOpacity style={[styles.optionButton, styles.optionButtonDisabled]} onPress={handleCreateFromLink}>
              <Ionicons name="link-outline" size={32} color="#999" />
              <View style={styles.optionTextContainer}>
                <Text style={[styles.optionTitle, styles.optionTitleDisabled]}>Create from Link</Text>
                <Text style={styles.optionSubtextDisabled}>Coming soon</Text>
              </View>
              <Ionicons name="chevron-forward" size={24} color="#ccc" />
            </TouchableOpacity>
          </View>
        ) : (
          <View style={styles.imagePreviewContainer}>
            <View style={styles.imagePreviewGrid}>
              {selectedImages.map((image, index) => (
                <View key={index} style={styles.imagePreviewItem}>
                  <ExpoImage
                    source={{ uri: image.uri }}
                    style={styles.imagePreviewThumbnail}
                    contentFit="cover"
                  />
                  <TouchableOpacity
                    style={styles.removeImageButton}
                    onPress={() => removeImage(index)}
                  >
                    <Ionicons name="close-circle" size={24} color="#ff3b30" />
                  </TouchableOpacity>
                </View>
              ))}
            </View>
            <View style={styles.addMoreContainer}>
              <TouchableOpacity style={styles.addMoreButton} onPress={handleTakePhoto}>
                <Ionicons name="camera-outline" size={20} color="#007AFF" />
                <Text style={styles.addMoreText}>Take Another</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.addMoreButton} onPress={handleUploadPhoto}>
                <Ionicons name="images-outline" size={20} color="#007AFF" />
                <Text style={styles.addMoreText}>Add More</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}
      </View>

      {/* Title, Description, Category, and Subcategory fields removed - AI will generate/recognize them automatically */}

      <TouchableOpacity
        style={[styles.submitButton, loading && styles.submitButtonDisabled]}
        onPress={handleSubmit}
        disabled={loading}
      >
        {loading ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <Text style={styles.submitButtonText}>Add Item</Text>
        )}
      </TouchableOpacity>
      </ScrollView>

      {/* AI Generation Loading Modal */}
      {generatingAI && (
        <Modal
          visible={generatingAI}
          transparent={true}
          animationType="fade"
          statusBarTranslucent={true}
        >
          <View style={styles.loadingOverlay}>
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" color="#007AFF" />
              <Text style={styles.loadingTitle}>Analyzing Item</Text>
              <Text style={styles.loadingMessage}>
                AI is recognizing category, attributes, and generating details...
              </Text>
            </View>
          </View>
        </Modal>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
  },
  headerButtonText: {
    color: '#000',
    fontSize: 14,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 24,
    marginTop: 20,
  },
  section: {
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#f9f9f9',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  imageOptionsContainer: {
    gap: 12,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f9f9f9',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    gap: 16,
  },
  optionButtonDisabled: {
    opacity: 0.6,
  },
  optionTextContainer: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  optionTitleDisabled: {
    color: '#999',
  },
  optionSubtext: {
    fontSize: 14,
    color: '#666',
  },
  optionSubtextDisabled: {
    color: '#999',
  },
  imagePreviewContainer: {
    marginTop: 12,
  },
  imagePreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  imagePreviewItem: {
    width: '48%',
    aspectRatio: 1,
    position: 'relative',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  imagePreviewThumbnail: {
    width: '100%',
    height: '100%',
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    padding: 2,
  },
  addMoreContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  addMoreButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: '#007AFF',
    borderRadius: 8,
    gap: 8,
  },
  addMoreText: {
    fontSize: 14,
    color: '#007AFF',
    fontWeight: '600',
  },
  optionsList: {
    gap: 8,
  },
  option: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
  },
  optionSelected: {
    borderColor: '#000',
    backgroundColor: '#f0f0f0',
  },
  optionText: {
    fontSize: 14,
    color: '#666',
  },
  optionTextSelected: {
    color: '#000',
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: '#000',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 40,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    minWidth: 280,
    maxWidth: '80%',
  },
  loadingTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingMessage: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
  },
});
